import turtle
def anweisung(steuer,tu):
    if steuer == 'w':
        tu.forward(10)
    if steuer == 's':
        tu.backward(10)
    if steuer == 'd':
        tu.right(45)
    if steuer == 'a':
        tu.left(45)
    if steuer == 'f':
        tu.up()
    if steuer == 'g':
        tu.down()

def a():
    turtle.down()
    turtle.left(90)
    turtle.forward(60)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(60)
    turtle.backward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.up()
    turtle.left(90)
    turtle.forward(40)


def b():
    turtle.down()
    turtle.left(90)
    turtle.forward(60)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(20)
    turtle.backward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.up()
    turtle.left(180)
    turtle.forward(40)


def c():
    turtle.down()
    turtle.forward(30)
    turtle.backward(30)
    turtle.left(90)
    turtle.forward(60)
    turtle.right(90)
    turtle.forward(30)
    turtle.up()
    turtle.right(90)
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(10)


def d():
    turtle.down()
    turtle.left(90)
    turtle.forward(60)
    turtle.right(90)
    for i in range(30):
        turtle.right(2)
        turtle.forward(1)
    turtle.right(30)
    turtle.forward(45)
    turtle.right(90)
    turtle.forward(25)
    turtle.up()
    turtle.left(180)
    turtle.forward(35)


def e():
    turtle.down()
    turtle.forward(30)
    turtle.backward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(20)
    turtle.backward(20)
    turtle.left(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.up()
    turtle.right(90)
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(10)


def f():
    turtle.down()
    turtle.left(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(20)
    turtle.backward(20)
    turtle.left(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.up()
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(10)

def g():
    turtle.down()
    x = turtle.xcor()
    y = turtle.ycor()
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(15)
    turtle.left(90)
    turtle.forward(5)
    turtle.up()
    turtle.setposition(x, y)
    turtle.left(180)
    turtle.down()
    turtle.forward(60)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(5)
    turtle.up()
    turtle.forward(55)
    turtle.left(90)
    turtle.forward(10)


def h():
    turtle.down()
    turtle.left(90)
    turtle.forward(60)
    turtle.backward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.backward(60)
    turtle.right(90)
    turtle.up()
    turtle.forward(10)


def i():
    turtle.up()
    turtle.forward(10)
    turtle.down()
    turtle.left(90)
    turtle.forward(60)
    turtle.backward(60)
    turtle.right(90)
    turtle.up()
    turtle.forward(10)


def j():
    turtle.down()
    turtle.left(90)
    turtle.forward(15)
    turtle.backward(15)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(60)
    turtle.backward(60)
    turtle.right(90)
    turtle.up()
    turtle.forward(10)


def k():
    turtle.down()
    turtle.left(90)
    turtle.forward(60)
    turtle.backward(30)
    turtle.right(45)
    turtle.forward(42.42640)
    turtle.backward(42.42640)
    turtle.right(90)
    turtle.forward(42.42640)
    turtle.left(45)
    turtle.up()
    turtle.forward(10)


def l():
    turtle.down()
    turtle.left(90)
    turtle.forward(60)
    turtle.backward(60)
    turtle.right(90)
    turtle.forward(30)
    turtle.up()
    turtle.forward(10)


def m():
    turtle.down()
    turtle.left(90)
    turtle.forward(60)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(25)
    turtle.backward(25)
    turtle.left(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(60)
    turtle.left(90)
    turtle.up()
    turtle.forward(10)


def n():
    turtle.down()
    turtle.left(90)
    turtle.forward(60)
    turtle.right(160)
    turtle.forward(64)
    turtle.left(160)
    turtle.forward(60)
    turtle.backward(60)
    turtle.right(90)
    turtle.up()
    turtle.forward(10)


def o():
    turtle.down()
    turtle.forward(30)
    turtle.backward(30)
    turtle.left(90)
    turtle.forward(60)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(60)
    turtle.left(90)
    turtle.up()
    turtle.forward(10)


def p():
    turtle.down()
    turtle.left(90)
    turtle.forward(60)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.backward(30)
    turtle.left(90)
    turtle.up()
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(10)


def q():
    turtle.down()
    turtle.forward(30)
    turtle.backward(30)
    turtle.left(90)
    turtle.forward(60)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(60)
    turtle.left(45)
    turtle.forward(5)
    turtle.backward(20)
    turtle.forward(15)
    turtle.left(45)
    turtle.up()
    turtle.forward(10)

def r():
    turtle.down()
    turtle.left(90)
    turtle.forward(60)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(125)
    turtle.forward(37)
    turtle.left(55)
    turtle.up()
    turtle.forward(20)


def s():
    turtle.down()
    turtle.left(90)
    turtle.forward(15)
    turtle.backward(15)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(15)
    turtle.up()
    turtle.forward(45)
    turtle.left(90)
    turtle.forward(10)


def t():
    turtle.up()
    turtle.forward(15)
    turtle.down()
    turtle.left(90)
    turtle.forward(60)
    turtle.right(90)
    turtle.backward(15)
    turtle.forward(30)
    turtle.right(90)
    turtle.up()
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(10)


def u():
    turtle.down()
    turtle.left(90)
    turtle.forward(60)
    turtle.backward(60)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(60)
    turtle.backward(60)
    turtle.up()
    turtle.right(90)
    turtle.forward(10)


def v():
    turtle.up()
    turtle.forward(15)
    turtle.down()
    turtle.left(75)
    turtle.forward(60)
    turtle.backward(60)
    turtle.left(30)
    turtle.forward(60)
    turtle.backward(60)
    turtle.right(105)
    turtle.up()
    turtle.forward(30)


def w():
    turtle.up()
    turtle.forward(10)
    turtle.down()
    turtle.left(75)
    turtle.forward(30)
    turtle.backward(30)
    turtle.left(30)
    turtle.forward(60)
    turtle.backward(60)
    turtle.right(105)
    turtle.up()
    turtle.forward(10)
    turtle.down()
    turtle.left(75)
    turtle.forward(60)
    turtle.backward(60)
    turtle.left(30)
    turtle.forward(30)
    turtle.backward(30)
    turtle.right(105)
    turtle.up()
    turtle.forward(30)


def x():
    turtle.down()
    turtle.left(60)
    turtle.forward(60)
    turtle.backward(30)
    turtle.left(60)
    turtle.forward(30)
    turtle.backward(60)
    turtle.right(120)
    turtle.up()
    turtle.forward(10)


def y():
    turtle.up()
    turtle.forward(15)
    turtle.down()
    turtle.left(90)
    turtle.forward(30)
    turtle.left(30)
    turtle.forward(30)
    turtle.backward(30)
    turtle.right(60)
    turtle.forward(30)
    turtle.backward(30)
    turtle.left(30)
    turtle.backward(30)
    turtle.up()
    turtle.right(90)
    turtle.forward(30)

def z():
    turtle.down()
    turtle.forward(30)
    turtle.backward(30)
    turtle.left(60)
    turtle.forward(60)
    turtle.left(120)
    turtle.forward(30)
    turtle.up()
    turtle.backward(30)
    turtle.left(90)
    turtle.forward(55)
    turtle.left(90)
    turtle.forward(10)

def frage():
    turtle.up()
    turtle.left(90)
    turtle.forward(40)
    turtle.down()
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(15)
    turtle.left(90)
    turtle.forward(20)
    turtle.up()
    turtle.forward(5)
    turtle.down()
    turtle.forward(5)
    turtle.up()
    turtle.left(90)
    turtle.forward(25)


def ausrufe():
    turtle.up()
    turtle.forward(15)
    turtle.left(90)
    turtle.down()
    turtle.forward(5)
    turtle.up()
    turtle.forward(5)
    turtle.down()
    turtle.forward(50)
    turtle.up()
    turtle.backward(60)
    turtle.right(90)
    turtle.forward(20)


def punkt():
    turtle.down()
    for i in range(4):
        turtle.forward(3)
        turtle.left(90)
    turtle.up()
    turtle.forward(20)


def space():
    turtle.up()
    turtle.forward(30)
